osx_image: xcode8.2.1
language: objective-c
xcode_workspace: FirebaseUI.xcworkspace
xcode_scheme: FirebaseUI

rvm: 2.3.1
before_install:
  - gem uninstall cocoapods -a
  - gem install cocoapods -v 1.2.0
  - gem install xcpretty
  - pod install --repo-update

script: ./test.sh
