osx_image: xcode8.3
language: objective-c
xcode_workspace: FirebaseUI.xcworkspace
xcode_scheme: FirebaseUI

rvm: 2.3.1
before_install:
  - open -a "simulator" --args -CurrentDeviceUDID F60B87EC-8969-41A7-90ED-D0826ECC32DB
  - bundle install
  - gem install xcpretty
  - bundle exec pod install --repo-update

script: ./test.sh
