osx_image: xcode11
language: objective-c
xcode_workspace: FirebaseUI.xcworkspace
xcode_scheme: FirebaseUI

rvm: 2.3.1
before_install:
  - gem install bundler
  - bundle install
  - gem install xcpretty

script: ./test.sh
