osx_image: xcode9
language: objective-c
xcode_workspace: FirebaseUI.xcworkspace
xcode_scheme: FirebaseUI

rvm: 2.3.1
before_install:
  - bundle install
  - gem install xcpretty
  - bundle exec pod install --repo-update

script: ./test.sh
